version: "3.9"

############################ NETWORKS
#networks:
#  default:
#    driver: bridge

########################### SERVICES
services:
  # InfluxDB - Database for sensor data
  influxdb:
    image: influxdb:latest
    container_name: neue-db-influxdb
#    networks:
#      - default
#    security_opt:
#      - no-new-privileges:true
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=asdf1234
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=first_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dnQA1UouZ7lvCFehcyojMTGspoOH9rr377M2RhIu2ejAQJDJCoaqEHuxBfAYGbptdNCr-ZZQAUNvKzP5BzSdWw==
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
#      - $DOCKERDIR/appdata/influxdb2/config:/etc/influxdb2
#      - $DOCKERDIR/appdata/influxdb2/db:/var/lib/influxdb2
      - ./DockerDB:/var/lib/influxdb2
